"""幂等 seed：建表 + 建桶 + 写 3 个示例游戏（含 1 个 source=create）并上传 bundle 到 OSS。

由 docker-compose 的 api 启动命令调用：python -m app.seed
"""
from datetime import timedelta

import app.models  # noqa: F401  注册表
from app.agents import bundles
from app.core.security import hash_password
from app.db.base import Base
from app.db.session import SessionLocal, engine
from app.models import Game, GameVersion, Tag, User
from app.models.common import GameSource, GameStatus, now_utc
from app.services.packaging import write_bundle
from app.storage.s3 import ensure_bucket

SEED_GAMES = [
    {
        "bundle": "neondodge", "title": "Neon Drift Dodge", "genre": "ENDLESS RUNNER",
        "summary": "Weave between neon traffic at impossible speeds. One tap to switch lanes — how far can you survive?",
        "tags": ["Arcade", "Endless", "Neon"], "cover": "linear-gradient(135deg,#0ea5b7,#4f46e5)",
        "plays": 124800, "likes": 8420, "source": GameSource.SEED, "prompt": "", "age_days": 14,
    },
    {
        "bundle": "colormatch", "title": "Color Echo", "genre": "MEMORY PUZZLE",
        "summary": "A hypnotic Simon-style memory game. Watch the sequence, echo it back, and chase an endless streak.",
        "tags": ["Puzzle", "Memory", "Casual"], "cover": "linear-gradient(135deg,#7c5cff,#c026d3)",
        "plays": 82100, "likes": 5140, "source": GameSource.SEED, "prompt": "", "age_days": 30,
    },
    {
        "bundle": "starcatch", "title": "Star Catcher", "genre": "CASUAL · COZY",
        "summary": "A cozy 30-second dash to catch falling stars — and dodge the red ones. Generated by the Create pipeline.",
        "tags": ["Casual", "Cozy", "AI"], "cover": "linear-gradient(135deg,#ff8a3d,#ff3ea5)",
        "plays": 30450, "likes": 2110, "source": GameSource.CREATE,
        "prompt": "a cozy little game where you move a basket to catch falling stars, soft warm vibes, 30 second rounds",
        "age_days": 4,
    },
]


def _get_or_create_tag(db, name: str) -> Tag:
    tag = db.query(Tag).filter_by(name=name).first()
    if not tag:
        tag = Tag(name=name)
        db.add(tag)
    return tag


def _get_or_create_user(db, email, name, initial, with_password=False) -> User:
    user = db.query(User).filter_by(email=email).first()
    if not user:
        user = User(
            email=email,
            password_hash=hash_password("password") if with_password else None,
            display_name=name,
            avatar_initial=initial,
        )
        db.add(user)
        db.flush()
    return user


def run() -> None:
    Base.metadata.create_all(bind=engine)
    ensure_bucket()
    db = SessionLocal()
    try:
        if db.query(Game).count() > 0:
            print("seed: games already present, skipping")
            return

        demo = _get_or_create_user(db, "demo@playforge.dev", "PlayForge Demo", "P", with_password=True)
        ai = _get_or_create_user(db, "ai@playforge.dev", "PlayForge AI", "AI")

        for s in SEED_GAMES:
            author = ai if s["source"] == GameSource.CREATE else demo
            game = Game(
                author_id=author.id,
                title=s["title"],
                summary=s["summary"],
                genre=s["genre"],
                cover=s["cover"],
                source=s["source"],
                status=GameStatus.PUBLISHED,
                current_version="v1",
                prompt=s.get("prompt") or None,
                plays_count=s["plays"],
                likes_count=s["likes"],
                published_at=now_utc() - timedelta(days=s["age_days"]),
            )
            for name in s["tags"]:
                game.tags.append(_get_or_create_tag(db, name))
            db.add(game)
            db.flush()

            html = bundles.BUNDLES[s["bundle"]]
            info = write_bundle(game.id, "v1", html, s["title"], author.display_name)
            db.add(GameVersion(
                game_id=game.id, version="v1", manifest_key=info["manifest_key"],
                bundle_key=info["bundle_key"], entry="index.html", runtime="iframe-sandbox",
                sha256=info["sha256"], size_bytes=info["size"],
            ))

        db.commit()
        print(f"seed: created {len(SEED_GAMES)} sample games (bundles uploaded to OSS)")
    finally:
        db.close()


if __name__ == "__main__":
    run()
