"""Idempotent database seed for curated PlayForge sample games.

The API container runs this module at startup. It creates tables, ensures demo
users exist, uploads playable HTML bundles to object storage, and creates or
refreshes the published sample game rows.
"""
from datetime import timedelta

import app.models  # noqa: F401 - registers SQLAlchemy models
from app.agents import bundles
from app.core.security import hash_password
from app.db.base import Base
from app.db.session import SessionLocal, engine
from app.models import Game, GameVersion, Tag, User
from app.models.common import GameSource, GameStatus, now_utc
from app.services.packaging import write_bundle
from app.storage.s3 import ensure_bucket


SEED_GAMES = [
    {
        "bundle": "moonlitkoi",
        "title": "Moonlit Koi",
        "genre": "ZEN ARCADE",
        "summary": "Guide a luminous koi through a moonlit pond, gather lantern petals, and slip past drifting ink ripples.",
        "tags": ["Arcade", "Zen", "Collect"],
        "cover": "/playforge/covers/moonlit-koi.jpg",
        "plays": 156300,
        "likes": 11840,
        "source": GameSource.SEED,
        "prompt": "",
        "age_days": 1,
    },
    {
        "bundle": "runecircuit",
        "title": "Rune Circuit",
        "genre": "LOGIC PUZZLE",
        "summary": "Rotate glowing glyph tiles to carry a living circuit from the left beacon to the right beacon.",
        "tags": ["Puzzle", "Logic", "Runes"],
        "cover": "/playforge/covers/rune-circuit.jpg",
        "plays": 137900,
        "likes": 9730,
        "source": GameSource.SEED,
        "prompt": "",
        "age_days": 2,
    },
    {
        "bundle": "neondodge",
        "title": "Neon Drift Dodge",
        "genre": "ENDLESS RUNNER",
        "summary": "Weave between neon traffic at impossible speeds. One tap to switch lanes and survive the glow rush.",
        "tags": ["Arcade", "Endless", "Neon"],
        "cover": "/playforge/covers/neon-drift-dodge.jpg",
        "plays": 124800,
        "likes": 8420,
        "source": GameSource.SEED,
        "prompt": "",
        "age_days": 14,
    },
    {
        "bundle": "cloudcourier",
        "title": "Cloud Courier",
        "genre": "SKY ARCADE",
        "summary": "Pilot a tiny courier glider through soft cloud lanes, collect mail, and dodge violet storm puffs.",
        "tags": ["Arcade", "Flight", "Cozy"],
        "cover": "/playforge/covers/cloud-courier.jpg",
        "plays": 111200,
        "likes": 8020,
        "source": GameSource.SEED,
        "prompt": "",
        "age_days": 3,
    },
    {
        "bundle": "orbitbloom",
        "title": "Orbit Bloom",
        "genre": "ONE-TAP ARCADE",
        "summary": "Swap between two glowing orbits, chain golden blossoms, and avoid crimson thorns in a quiet garden.",
        "tags": ["Arcade", "Timing", "One Tap"],
        "cover": "/playforge/covers/orbit-bloom.jpg",
        "plays": 96400,
        "likes": 7210,
        "source": GameSource.SEED,
        "prompt": "",
        "age_days": 5,
    },
    {
        "bundle": "colormatch",
        "title": "Color Echo",
        "genre": "MEMORY PUZZLE",
        "summary": "A hypnotic Simon-style memory game. Watch the sequence, echo it back, and chase an endless streak.",
        "tags": ["Puzzle", "Memory", "Casual"],
        "cover": "/playforge/covers/color-echo.jpg",
        "plays": 82100,
        "likes": 5140,
        "source": GameSource.SEED,
        "prompt": "",
        "age_days": 30,
    },
    {
        "bundle": "starcatch",
        "title": "Star Catcher",
        "genre": "CASUAL COZY",
        "summary": "A cozy 40-second dash to catch falling stars and dodge the red ones. Generated by the Create pipeline.",
        "tags": ["Casual", "Cozy", "AI"],
        "cover": "/playforge/covers/star-catcher.jpg",
        "plays": 30450,
        "likes": 2110,
        "source": GameSource.CREATE,
        "prompt": "a cozy little game where you move a basket to catch falling stars, soft warm vibes, 30 second rounds",
        "age_days": 4,
    },
]


def _get_or_create_tag(db, name: str) -> Tag:
    tag = db.query(Tag).filter_by(name=name).first()
    if not tag:
        tag = Tag(name=name)
        db.add(tag)
        db.flush()
    return tag


def _get_or_create_user(db, email: str, name: str, initial: str, with_password: bool = False) -> User:
    user = db.query(User).filter_by(email=email).first()
    if not user:
        user = User(
            email=email,
            password_hash=hash_password("password") if with_password else None,
            display_name=name,
            avatar_initial=initial,
        )
        db.add(user)
        db.flush()
    return user


def _sync_tags(db, game: Game, names: list[str]) -> None:
    game.tags.clear()
    for name in names:
        game.tags.append(_get_or_create_tag(db, name))


def _sync_version(db, game: Game, seed: dict, author_name: str) -> None:
    html = bundles.BUNDLES[seed["bundle"]]
    info = write_bundle(game.id, "v1", html, seed["title"], author_name)
    version = db.query(GameVersion).filter_by(game_id=game.id, version="v1").first()
    if not version:
        version = GameVersion(game_id=game.id, version="v1")
        db.add(version)
    version.manifest_key = info["manifest_key"]
    version.bundle_key = info["bundle_key"]
    version.entry = "index.html"
    version.runtime = "iframe-sandbox"
    version.sha256 = info["sha256"]
    version.size_bytes = info["size"]


def run() -> None:
    Base.metadata.create_all(bind=engine)
    ensure_bucket()
    db = SessionLocal()
    try:
        demo = _get_or_create_user(db, "demo@playforge.dev", "PlayForge Demo", "P", with_password=True)
        ai = _get_or_create_user(db, "ai@playforge.dev", "PlayForge AI", "AI")
        created = 0
        refreshed = 0

        for seed in SEED_GAMES:
            author = ai if seed["source"] == GameSource.CREATE else demo
            game = db.query(Game).filter_by(title=seed["title"]).first()
            if game:
                refreshed += 1
            else:
                created += 1
                game = Game(
                    author_id=author.id,
                    title=seed["title"],
                    published_at=now_utc() - timedelta(days=seed["age_days"]),
                )
                db.add(game)
                db.flush()

            game.author_id = author.id
            game.summary = seed["summary"]
            game.genre = seed["genre"]
            game.cover = seed["cover"]
            game.source = seed["source"]
            game.status = GameStatus.PUBLISHED
            game.current_version = "v1"
            game.prompt = seed.get("prompt") or None
            game.plays_count = max(game.plays_count or 0, seed["plays"])
            game.likes_count = max(game.likes_count or 0, seed["likes"])
            if not game.published_at:
                game.published_at = now_utc() - timedelta(days=seed["age_days"])

            _sync_tags(db, game, seed["tags"])
            _sync_version(db, game, seed, author.display_name)

        db.commit()
        print(f"seed: created {created}, refreshed {refreshed} sample games (bundles uploaded to OSS)")
    finally:
        db.close()


if __name__ == "__main__":
    run()
