"""Compatibility facade for GameWeave planning helpers and LangGraph nodes."""

from app.agents.planning_brief import (
    _brief_keywords,
    _coerce_brief,
    _coerce_mechanic_plan,
    _content_plan,
    _heuristic_brief,
    _heuristic_mechanic_plan,
    _prompt_cues,
)
from app.agents.planning_logs import (
    _asset_log_lines,
    _balance_log_lines,
    _brief_log_lines,
    _content_log_lines,
    _controls_line,
    _design_log_lines,
    _entity_line,
    _mechanic_log_lines,
    _spec_log_lines,
)
from app.agents.planning_nodes import (
    archetype_router_node,
    asset_processing_node,
    balance_plan_node,
    contract_gate_node,
    content_plan_node,
    done_node,
    failed_node,
    feedback_understanding_node,
    game_design_node,
    gameplay_planning_node,
    intent_spec_node,
    design_contract_node,
    should_continue_after_safety,
    should_continue_after_contract_gate,
    should_continue_after_asset_generation,
)
from app.agents.planning_routing import (
    _balance_plan,
    _difficulty_factor,
    _merge_balance_into_design,
    _reconcile_archetype_3d,
    _route_archetype,
    _route_archetype_3d,
)
from app.agents.planning_safety import safety_intake_node
from app.agents.planning_spec import (
    _coerce_design,
    _coerce_spec,
    _detect_genre,
    _detect_theme,
    _heuristic_design,
    _heuristic_spec,
    _simplify_design,
    _simplify_design_3d,
    _theme_cover,
)


__all__ = [
    '_detect_theme',
    '_detect_genre',
    '_theme_cover',
    '_heuristic_spec',
    '_coerce_spec',
    '_heuristic_design',
    '_coerce_design',
    '_simplify_design',
    '_simplify_design_3d',
    '_prompt_cues',
    '_controls_line',
    '_spec_log_lines',
    '_entity_line',
    '_design_log_lines',
    '_asset_log_lines',
    '_brief_keywords',
    '_heuristic_brief',
    '_coerce_brief',
    '_brief_log_lines',
    '_heuristic_mechanic_plan',
    '_coerce_mechanic_plan',
    '_mechanic_log_lines',
    '_content_plan',
    '_content_log_lines',
    '_route_archetype',
    '_route_archetype_3d',
    '_reconcile_archetype_3d',
    '_difficulty_factor',
    '_balance_plan',
    '_merge_balance_into_design',
    '_balance_log_lines',
    'safety_intake_node',
    'intent_spec_node',
    'gameplay_planning_node',
    'archetype_router_node',
    'asset_processing_node',
    'game_design_node',
    'content_plan_node',
    'balance_plan_node',
    'design_contract_node',
    'contract_gate_node',
    'feedback_understanding_node',
    'failed_node',
    'done_node',
    'should_continue_after_safety',
    'should_continue_after_contract_gate',
    'should_continue_after_asset_generation',
]
