import type { BuildingDefinition, BuildingKind } from "./CityTypes";

/** Static facility tuning. Simulation code applies connectivity, capacity and tier rules. */
export const BUILDING_CATALOG: Readonly<Record<BuildingKind, BuildingDefinition>> = Object.freeze({
  road: Object.freeze({
    kind: "road",
    name: "城市道路",
    description: "连接建筑、公用设施与商业活动的四向道路。",
    footprint: Object.freeze({ width: 1, height: 1 }),
    cost: 50,
    demolitionRefundRate: 0.4,
    dailyIncome: 0,
    dailyMaintenance: 0,
    populationCapacity: 0,
    minimumPopulationToOperate: 0,
    powerDemand: 0,
    waterDemand: 0,
    powerCapacity: 0,
    waterCapacity: 0,
    pollution: null,
    requiresRoad: false,
    art: Object.freeze({ sheetKey: "sheet-2", frameName: "entity_1", frameIndex: 8 }),
    connectableTileFamily: "entity_1",
  }),
  home: Object.freeze({
    kind: "home",
    name: "暖顶住宅区",
    description: "最多容纳40位居民；接入道路、电力和供水后逐日入住并贡献税收。",
    footprint: Object.freeze({ width: 2, height: 2 }),
    cost: 600,
    demolitionRefundRate: 0.4,
    dailyIncome: 72,
    dailyMaintenance: 12,
    populationCapacity: 40,
    minimumPopulationToOperate: 0,
    powerDemand: 40,
    waterDemand: 35,
    powerCapacity: 0,
    waterCapacity: 0,
    pollution: null,
    requiresRoad: true,
    art: Object.freeze({ sheetKey: "sheet-2", frameName: "entity_2", frameIndex: 13 }),
  }),
  commercial: Object.freeze({
    kind: "commercial",
    name: "蓝牌商业区",
    description: "人口达到30后营业；基础设施齐全时提供高于住宅的日收入。",
    footprint: Object.freeze({ width: 2, height: 2 }),
    cost: 900,
    demolitionRefundRate: 0.4,
    dailyIncome: 165,
    dailyMaintenance: 28,
    populationCapacity: 0,
    minimumPopulationToOperate: 30,
    powerDemand: 55,
    waterDemand: 45,
    powerCapacity: 0,
    waterCapacity: 0,
    pollution: null,
    requiresRoad: true,
    art: Object.freeze({ sheetKey: "sheet-2", frameName: "entity_3", frameIndex: 14 }),
  }),
  power: Object.freeze({
    kind: "power",
    name: "橙炉电厂",
    description: "提供400电力；应远离住宅，并为后期停电保留备用容量。",
    footprint: Object.freeze({ width: 3, height: 3 }),
    cost: 3000,
    demolitionRefundRate: 0.4,
    dailyIncome: 0,
    dailyMaintenance: 120,
    populationCapacity: 0,
    minimumPopulationToOperate: 0,
    powerDemand: 0,
    waterDemand: 0,
    powerCapacity: 400,
    waterCapacity: 0,
    pollution: Object.freeze({ strongRadius: 2, weakRadius: 5, strongAmount: 18, weakAmount: 8 }),
    requiresRoad: true,
    art: Object.freeze({ sheetKey: "sheet-2", frameName: "entity_4", frameIndex: 15 }),
  }),
  water: Object.freeze({
    kind: "water",
    name: "青蓝水务站",
    description: "提供350供水容量；接入道路后为同一网络中的需求设施服务。",
    footprint: Object.freeze({ width: 3, height: 3 }),
    cost: 2400,
    demolitionRefundRate: 0.4,
    dailyIncome: 0,
    dailyMaintenance: 90,
    populationCapacity: 0,
    minimumPopulationToOperate: 0,
    powerDemand: 0,
    waterDemand: 0,
    powerCapacity: 0,
    waterCapacity: 350,
    pollution: null,
    requiresRoad: true,
    art: Object.freeze({ sheetKey: "sheet-3", frameName: "entity_5", frameIndex: 0 }),
  }),
});
