from enum import Enum


class TaskErrorCode(str, Enum):
    SAFETY_REJECTED = "SAFETY_REJECTED"
    MODERATION_BLOCKED = "MODERATION_BLOCKED"
    PROMPT_TOO_LONG = "PROMPT_TOO_LONG"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_INVALID_OUTPUT = "MODEL_INVALID_OUTPUT"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    SMOKE_FAILED = "SMOKE_FAILED"
    QA_FAILED = "QA_FAILED"
    SANDBOX_UNAVAILABLE = "SANDBOX_UNAVAILABLE"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    PUBLISH_FAILED = "PUBLISH_FAILED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"
